# Generated by Django 6.0.5 on 2026-05-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('exitoso', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BaseConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('fuente_url', models.URLField(max_length=500)),
                ('relevancia_score', models.FloatField(default=0.5)),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'base_conocimiento',
                'ordering': ['-relevancia_score'],
            },
        ),
        migrations.CreateModel(
            name='AprendizajeAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad_predicha', models.IntegerField()),
                ('prioridad_real', models.IntegerField()),
                ('precision_prediccion', models.FloatField()),
                ('ajustes_aplicados', models.JSONField(default=dict)),
                ('fecha_aprendizaje', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizajes', to='api.mantenimiento')),
            ],
            options={
                'db_table': 'aprendizaje_automatico',
                'ordering': ['-fecha_aprendizaje'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(default='mantenimiento', max_length=20)),
                ('prioridad', models.IntegerField(default=2)),
                ('accion_sugerida', models.CharField(blank=True, max_length=200)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('ahorro_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
                ('confianza', models.FloatField()),
                ('vista', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='api.equipo')),
            ],
            options={
                'db_table': 'recomendacion',
                'ordering': ['-confianza', '-fecha_creacion'],
            },
        ),
    ]
