# Generated by Django 4.2 on 2025-10-24 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CambioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_field', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='cambios', to='equipos.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
