# Generated by Django 5.2.7 on 2025-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='EstadoEntregable',
        ),
    ]
