# Generated by Django 5.2.8 on 2025-11-24 22:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entregables", "0002_alter_entregable_estado_delete_estadoentregable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="Formato: 12345678-9",
                        max_length=12,
                        unique=True,
                        verbose_name="RUT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("operador", "Operador de Maquinaria"),
                            ("chofer", "Chofer"),
                            ("mecanico", "Mecánico"),
                            ("supervisor", "Supervisor de Faena"),
                            ("jefe_cuadrilla", "Jefe de Cuadrilla"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "licencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: A1, A2, A3, A4, A5",
                        max_length=10,
                        verbose_name="Licencia de Conducir",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono"
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Operario",
                "verbose_name_plural": "Operarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Patente"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("camion", "Camión Forestal"),
                            ("cosechadora", "Cosechadora Forestal"),
                            ("skidder", "Skidder"),
                            ("grua", "Grúa Forestal"),
                            ("camioneta", "Camioneta"),
                            ("excavadora", "Excavadora"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Vehículo",
                    ),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "año",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Año",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("operativo", "Operativo"),
                            ("en_mantencion", "En Mantención"),
                            ("fuera_servicio", "Fuera de Servicio"),
                            ("reparacion", "En Reparación"),
                        ],
                        default="operativo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "horas_uso",
                    models.IntegerField(
                        default=0,
                        help_text="Total de horas de operación",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas de Uso",
                    ),
                ),
                (
                    "capacidad_carga",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacidad en toneladas",
                        max_digits=8,
                        null=True,
                        verbose_name="Capacidad de Carga (ton)",
                    ),
                ),
                (
                    "fecha_adquisicion",
                    models.DateField(verbose_name="Fecha de Adquisición"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.RemoveField(
            model_name="entregable",
            name="proyecto",
        ),
        migrations.RemoveField(
            model_name="entregable",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="miembro",
            name="equipo",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="equipo",
        ),
        migrations.CreateModel(
            name="Faena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre de la Faena"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("corta", "Corta de Árboles"),
                            ("transporte", "Transporte de Troncos"),
                            ("plantacion", "Plantación"),
                            ("raleo", "Raleo"),
                            ("limpieza", "Limpieza de Terreno"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Faena",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Sector forestal o coordenadas",
                        max_length=200,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificada", "Planificada"),
                            ("en_curso", "En Curso"),
                            ("pausada", "Pausada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="planificada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_termino",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Término"
                    ),
                ),
                (
                    "metros_cubicos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volumen de madera procesada",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Metros Cúbicos (m³)",
                    ),
                ),
                (
                    "hectareas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Superficie trabajada",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hectáreas",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "operario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faenas_asignadas",
                        to="entregables.operario",
                        verbose_name="Operario Responsable",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faenas",
                        to="entregables.vehiculo",
                        verbose_name="Vehículo Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faena",
                "verbose_name_plural": "Faenas",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RegistroIncidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("accidente", "Accidente"),
                            ("incidente", "Incidente"),
                            ("casi_accidente", "Casi Accidente"),
                            ("condicion_insegura", "Condición Insegura"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Incidente",
                    ),
                ),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("moderado", "Moderado"),
                            ("grave", "Grave"),
                            ("critico", "Crítico"),
                        ],
                        max_length=20,
                        verbose_name="Gravedad",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Incidente"),
                ),
                (
                    "fecha_incidente",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Incidente",
                    ),
                ),
                (
                    "medidas_tomadas",
                    models.TextField(blank=True, verbose_name="Medidas Tomadas"),
                ),
                (
                    "reportado_por",
                    models.CharField(max_length=200, verbose_name="Reportado Por"),
                ),
                (
                    "faena",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidentes",
                        to="entregables.faena",
                        verbose_name="Faena",
                    ),
                ),
                (
                    "operario_involucrado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes",
                        to="entregables.operario",
                        verbose_name="Operario Involucrado",
                    ),
                ),
                (
                    "vehiculo_involucrado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes",
                        to="entregables.vehiculo",
                        verbose_name="Vehículo Involucrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Incidente",
                "verbose_name_plural": "Registros de Incidentes",
                "ordering": ["-fecha_incidente"],
            },
        ),
        migrations.CreateModel(
            name="Mantencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventiva", "Preventiva"),
                            ("correctiva", "Correctiva"),
                            ("emergencia", "Emergencia"),
                            ("revision", "Revisión Técnica"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Mantención",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("en_proceso", "En Proceso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("fecha_programada", models.DateField(verbose_name="Fecha Programada")),
                (
                    "fecha_realizada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Realizada"
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Costo (CLP)",
                    ),
                ),
                (
                    "repuestos_utilizados",
                    models.TextField(blank=True, verbose_name="Repuestos Utilizados"),
                ),
                (
                    "horas_vehiculo",
                    models.IntegerField(
                        blank=True,
                        help_text="Horas de uso al momento de la mantención",
                        null=True,
                        verbose_name="Horas del Vehículo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "mecanico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mantenciones_realizadas",
                        to="entregables.operario",
                        verbose_name="Mecánico Responsable",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenciones",
                        to="entregables.vehiculo",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantención",
                "verbose_name_plural": "Mantenciones",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
        migrations.DeleteModel(
            name="Miembro",
        ),
        migrations.DeleteModel(
            name="Equipo",
        ),
        migrations.DeleteModel(
            name="Proyecto",
        ),
    ]
