# Generated by Django 5.2.8 on 2025-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entregables", "0003_operario_vehiculo_remove_entregable_proyecto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faena",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
