from django.db import models

CATEGORIA_ELECTRICO = 1
CATEGORIA_HIDRAULICO = 2
CATEGORIA_MECANICO = 4
CATEGORIA_GENERAL = 8

ESPECIALIDAD_ELECTRICO = 1
ESPECIALIDAD_HIDRAULICO = 2
ESPECIALIDAD_MECANICO = 4
ESPECIALIDAD_GENERAL = 8

ESTADO_PENDIENTE = 1
ESTADO_EN_PROGRESO = 2
ESTADO_COMPLETADO = 4
ESTADO_CANCELADO = 8

PRIORIDAD_ALTA = 100
PRIORIDAD_MEDIA = 50
PRIORIDAD_BAJA = 10
PRIORIDAD_CRITICA = 999


class CategoriaEquipo(models.IntegerChoices):
    ELECTRICO = CATEGORIA_ELECTRICO, 'Eléctrico'
    HIDRAULICO = CATEGORIA_HIDRAULICO, 'Hidráulico'
    MECANICO = CATEGORIA_MECANICO, 'Mecánico'
    GENERAL = CATEGORIA_GENERAL, 'General'


class EspecialidadTecnico(models.IntegerChoices):
    ELECTRICO = ESPECIALIDAD_ELECTRICO, 'Eléctrico'
    HIDRAULICO = ESPECIALIDAD_HIDRAULICO, 'Hidráulico'
    MECANICO = ESPECIALIDAD_MECANICO, 'Mecánico'
    GENERAL = ESPECIALIDAD_GENERAL, 'General'


class EstadoOrden(models.IntegerChoices):
    PENDIENTE = ESTADO_PENDIENTE, 'Pendiente'
    EN_PROGRESO = ESTADO_EN_PROGRESO, 'En Progreso'
    COMPLETADO = ESTADO_COMPLETADO, 'Completado'
    CANCELADO = ESTADO_CANCELADO, 'Cancelado'


class Prioridad(models.IntegerChoices):
    ALTA = PRIORIDAD_ALTA, 'Alta'
    MEDIA = PRIORIDAD_MEDIA, 'Media'
    BAJA = PRIORIDAD_BAJA, 'Baja'
    CRITICA = PRIORIDAD_CRITICA, 'Crítica'
